config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name,
    presence: true, 
    uniqueness: true

  has_rich_text :description
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  helper_method :current_user, :signed_in?

  private

  def authenticate_user!
    return if signed_in?

    redirect_to new_session_path, alert: 'You must sign in first.'
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def signed_in?
    current_user.present?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %w(show edit update destroy)

  def index
    @items = Item.all.with_rich_text_description_and_embeds
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash.notice = "#{@item.name} was created."
      redirect_to @item
    else
      redirect_to new_item_path(@item)
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      flash.notice = "#{@item.name} was updated."
      redirect_to @item
    else
      redirect_to edit_item_path(@item)
    end
  end

  def destroy
    if @item.destroy
      flash.notice = "#{@item.name} was deleted."
      redirect_to items_path
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user.nil?
      sleep rand(200..300) / 1000.0
      flash.now.alert = 'Username or password is invalid'
      render :new
    elsif @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Logged in.'
    else
      flash.now.alert = 'Username or password is invalid'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'Logged out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @user = User.new
  end

  def create
    @user = User.new(signup_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Thank you for signing up!'
    else
      render :new
    end
  end

  private

  def signup_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/items/_form.html.erb
<%= form_with model: @item, class: 'lot-form' do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <br/>

  <%= form.label :description %>
  <%= form.rich_text_area :description %>

  <%= form.submit 'Save' %>
  <%= link_to 'Cancel', @item.persisted? ? @item : items_path %>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/edit.html.erb
<%= render partial: 'form', object: @item %>

app/views/items/index.html.erb
<div class="lots">
  <h1>Lots</h1>
  <ul>
    <% @items.each do |item| %>
      <li><%= link_to item.name, item %></li>
    <% end %>
  </ul>
  <%= link_to 'New lot', new_item_path %>
</div>

app/views/items/new.html.erb
<div class="new-lot">
  <h1>New Lot</h1>
  <%= render partial: 'form', object: @item %>
</div>

app/views/items/show.html.erb
<div class="lot">
  <h1>Item</h1>

  <h3>Name</h3>
  <%= @item.name %>

  <h3>Description</h3>
  <%= @item.description %>

  <br />
  <%= link_to 'Edit', edit_item_path(@item) %>
  <%= link_to 'Delete', @item, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Back', items_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lots</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <%= link_to 'Home', items_path %>
      <% if signed_in? %>
        <%= link_to 'Sign out', session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', new_session_path %>
        <%= link_to 'Sign up', new_user_path %>
      <% end %>
    </div>

    <div class="flash-message">
      <% flash.each do |type, msg| %>
        <p class="<%=type%>"><%= msg %></p>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with model: @user, local: true do |form| %>
  <% if @user.errors.any? %>
    <div id='error_explaination'>
      <h2>
        <%= pluralize(@user.errors.count, 'error') %>
        prohibited this user from signing up:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class='field'>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class='field'>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class='actions'>
    <%= form.submit 'Sign Up' %>
  </div>
<% end %>